# Generated by Django 4.1 on 2022-08-29 18:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInsumos', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_insumo', models.IntegerField(verbose_name='Id Insumo')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_folio', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularioInsumos.formulario', verbose_name='Folio')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioHistorial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_hora', models.DateTimeField(default=datetime.datetime.now)),
                ('estado_formulario', models.IntegerField(verbose_name='Estado Solicitud')),
                ('rut_gestor', models.CharField(max_length=50, verbose_name='Rut Gestor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_folio_formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularioInsumos.formulario', verbose_name='Folio')),
            ],
        ),
    ]
