# Generated by Django 4.1 on 2022-11-02 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0013_insumo_precio'),
        ('formularioInsumos', '0002_formularioinsumo_formulariohistorial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinsumo',
            name='id_insumo',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo', verbose_name='Insumo'),
        ),
    ]
