# Generated by Django 4.1 on 2022-11-03 18:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInsumos', '0003_alter_formularioinsumo_id_insumo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formularioinsumo',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
