# Generated by Django 4.1 on 2022-12-12 14:59

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInsumos', '0005_formularioinsumo_cantidad_aprobada_jefatura_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariohistorial',
            name='fecha_hora',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
