# Generated by Django 4.1 on 2023-04-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('formularioInsumos', '0006_alter_formulariohistorial_fecha_hora'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulario',
            options={'ordering': ['-pk']},
        ),
    ]
