# Generated by Django 4.1 on 2023-04-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0008_alter_subdepartamento_options_alter_unidad_options'),
        ('formularioInsumos', '0007_alter_formulario_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulario',
            name='id_sub_departamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.subdepartamento', verbose_name='Sub Departamento'),
        ),
        migrations.AlterField(
            model_name='formulario',
            name='id_unidad',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.unidad', verbose_name='Unidad'),
        ),
    ]
