# Generated by Django 4.1 on 2022-11-29 20:37

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Inventario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_producto', models.IntegerField(verbose_name='Código Producto')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('tipo_transaccion', models.CharField(max_length=5, verbose_name='Tipo Transacción')),
                ('id_compra', models.IntegerField(verbose_name='Id Compra')),
                ('id_folio_entrega', models.CharField(max_length=20, verbose_name='Id Folio Entrega')),
                ('fecha', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Fecha')),
            ],
        ),
    ]
