# Generated by Django 4.1 on 2022-11-24 13:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuraciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('iva', models.FloatField(verbose_name='IVA')),
                ('rut_encargado_bodega', models.CharField(max_length=50, verbose_name='Rut Encargado Bodega')),
                ('rut_responsable', models.CharField(max_length=50, verbose_name='Rut Responsable')),
                ('rut_secretaria_direccion', models.CharField(max_length=50, verbose_name='Rut Secretaria Dirección')),
                ('ultima_actualizacion', models.DateField(default=datetime.datetime(2022, 11, 24, 10, 38, 3, 645745), verbose_name='Última Actualización')),
            ],
        ),
    ]
