# Generated by Django 4.1 on 2022-11-24 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('configuraciones', '0004_alter_configuraciones_ultima_actualizacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configuraciones',
            name='ultima_actualizacion',
            field=models.DateField(default=datetime.datetime(2022, 11, 24, 13, 42, 41, 418783, tzinfo=datetime.timezone.utc), verbose_name='Última Actualización'),
        ),
    ]
