# Generated by Django 4.1 on 2022-11-03 20:17

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0013_insumo_precio'),
        ('departamentos', '0003_alter_unidad_subdepartamento'),
    ]

    operations = [
        migrations.CreateModel(
            name='PresupuestoSubDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto_categoria', to='insumos.categoria', verbose_name='Categoría')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto_dpto', to='departamentos.departamento', verbose_name='Departamento')),
                ('id_subdepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto', to='departamentos.subdepartamento', verbose_name='SubDepartamento')),
            ],
        ),
        migrations.CreateModel(
            name='PresupuestoDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('presupuesto', models.FloatField(verbose_name='Presupuesto')),
                ('presupuesto_total', models.FloatField(verbose_name='Presupuesto Total')),
                ('fecha', models.DateField(default=datetime.date.today, verbose_name='Fecha')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_categoria', to='insumos.categoria', verbose_name='Categoría')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_dpto', to='departamentos.departamento', verbose_name='Departamento')),
            ],
        ),
    ]
