# Generated by Django 4.1 on 2022-11-07 14:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0013_insumo_precio'),
        ('presupuesto', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestodepartamento',
            name='id_categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_dpto_categoria', to='insumos.categoria', verbose_name='Categoría'),
        ),
        migrations.CreateModel(
            name='PresupuestoCategoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dpto_subdpto', models.IntegerField(verbose_name='Departamento/Sub Departamento')),
                ('marco_presupuestario', models.FloatField(verbose_name='Marco Presupuestario')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_categoria', to='insumos.categoria', verbose_name='Categoría')),
            ],
        ),
    ]
