# Generated by Django 4.1 on 2022-11-07 19:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0013_insumo_precio'),
        ('presupuesto', '0002_alter_presupuestodepartamento_id_categoria_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestocategoria',
            name='id_categoria',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_categoria', to='insumos.categoria', verbose_name='Categoría'),
        ),
    ]
