# Generated by Django 4.1 on 2022-11-07 19:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('presupuesto', '0003_alter_presupuestocategoria_id_categoria'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestocategoria',
            name='id_dpto_subdpto',
        ),
    ]
