# Generated by Django 4.1 on 2022-11-07 21:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_unidad_subdepartamento'),
        ('presupuesto', '0004_remove_presupuestocategoria_id_dpto_subdpto'),
    ]

    operations = [
        migrations.AlterField(
            model_name='presupuestodepartamento',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_dpto', to='departamentos.departamento', unique=True, verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='presupuestosubdepartamento',
            name='id_subdepartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto', to='departamentos.subdepartamento', unique=True, verbose_name='SubDepartamento'),
        ),
    ]
