# Generated by Django 4.1 on 2022-11-08 19:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0003_alter_unidad_subdepartamento'),
        ('presupuesto', '0005_alter_presupuestodepartamento_id_departamento_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='presupuestodepartamento',
            name='id_categoria',
        ),
        migrations.RemoveField(
            model_name='presupuestodepartamento',
            name='presupuesto_total',
        ),
        migrations.RemoveField(
            model_name='presupuestosubdepartamento',
            name='id_categoria',
        ),
        migrations.AddField(
            model_name='presupuestodepartamento',
            name='id_presupuesto_categoria',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_dpto_categoria', to='presupuesto.presupuestocategoria', verbose_name='Categoría'),
        ),
        migrations.AddField(
            model_name='presupuestosubdepartamento',
            name='id_presupuesto_categoria',
            field=models.OneToOneField(default=None, on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto_categoria', to='presupuesto.presupuestocategoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='presupuestodepartamento',
            name='id_departamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_dpto', to='departamentos.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='presupuestosubdepartamento',
            name='id_subdepartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='presupuesto_subdpto', to='departamentos.subdepartamento', verbose_name='SubDepartamento'),
        ),
    ]
