# Generated by Django 4.1 on 2022-08-03 21:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_categoria', models.CharField(max_length=255, verbose_name='Nombre')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='UnidadMedida',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_unidad_medida', models.CharField(max_length=50, verbose_name='Unidad Medida')),
                ('estado', models.BooleanField(verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Insumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_insumo', models.CharField(max_length=50, verbose_name='Código Insumo')),
                ('denominacion', models.CharField(max_length=255, verbose_name='Denominación')),
                ('saldo', models.IntegerField(verbose_name='Saldo')),
                ('stock_critico', models.IntegerField(verbose_name='Stock Crítico')),
                ('estado', models.BooleanField(verbose_name='Estado')),
                ('categoria', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumos.categoria', verbose_name='Categoría')),
                ('unidad_medida', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='insumos.unidadmedida', verbose_name='Unidad Medida')),
            ],
        ),
    ]
