# Generated by Django 4.1 on 2022-08-08 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0003_alter_insumo_categoria_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categoria',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
