# Generated by Django 4.1 on 2022-08-11 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0004_alter_categoria_estado_alter_insumo_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidadmedida',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
