# Generated by Django 4.1 on 2022-08-12 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0005_alter_unidadmedida_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fkcategoria', to='insumos.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='fkunidmed', to='insumos.unidadmedida', verbose_name='Unidad Medida'),
        ),
    ]
