# Generated by Django 4.1 on 2022-09-14 19:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0010_alter_insumo_categoria_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='stock_critico',
            field=models.IntegerField(default=1, verbose_name='Stock Crítico'),
        ),
    ]
