# Generated by Django 4.1 on 2022-09-27 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0011_alter_insumo_stock_critico'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='insumo',
            options={'ordering': ['id']},
        ),
    ]
