# Generated by Django 4.1 on 2022-10-20 18:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0012_alter_insumo_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='insumo',
            name='precio',
            field=models.FloatField(default=0, verbose_name='Precio'),
        ),
    ]
