# Generated by Django 4.1 on 2022-11-17 15:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0013_insumo_precio'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Estado',
        ),
    ]
