# Generated by Django 4.1 on 2022-11-23 15:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0014_delete_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='categoria',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumo_categoria', to='insumos.categoria', verbose_name='Categoría'),
        ),
        migrations.AlterField(
            model_name='insumo',
            name='unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='insumo_unidadmedida', to='insumos.unidadmedida', verbose_name='Unidad Medida'),
        ),
    ]
