# Generated by Django 4.1 on 2022-09-09 20:32

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormularioSRHistorial',
            fields=[
                ('id_historial', models.AutoField(primary_key=True, serialize=False)),
                ('folio_formularioSR', models.CharField(default='', max_length=50, verbose_name='Folio SR')),
                ('fecha_ingreso', models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso')),
                ('hora_ingreso', models.TimeField(verbose_name='Hora Ingreso')),
                ('comentarios', models.TextField(null=True, verbose_name='Comentarios')),
                ('indicaciones', models.TextField(null=True, verbose_name='Indicaciones')),
                ('estado_solicitud', models.IntegerField(choices=[(1, 'INGRESADO'), (2, 'RESPONDIDO'), (3, 'ENTREGADO'), (4, 'RECHAZADO')], verbose_name='Estado Solicitud')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularioSR.formulariosr', verbose_name='Id formularioSR')),
            ],
        ),
        migrations.CreateModel(
            name='FormularioSRDerivacion',
            fields=[
                ('id_derivacion', models.AutoField(primary_key=True, serialize=False)),
                ('folio_formularioSR', models.CharField(default='', max_length=50, verbose_name='Folio SR')),
                ('rut_derivado', models.CharField(max_length=50, verbose_name='Rut Derivado')),
                ('fecha_derivado', models.DateField(default=datetime.date.today, verbose_name='Fecha Derivado')),
                ('hora_derivado', models.TimeField(verbose_name='Hora Derivado')),
                ('id_formulario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='formularioSR.formulariosr', verbose_name='Id formularioSR')),
            ],
        ),
    ]
