# Generated by Django 4.1 on 2022-09-14 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0003_alter_formulariosrhistorial_comentarios'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosr',
            name='comentarios',
            field=models.TextField(verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='indicaciones',
            field=models.TextField(null=True, verbose_name='Indicación'),
        ),
    ]
