# Generated by Django 4.1 on 2022-09-14 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0004_alter_formulariosr_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='comentarios',
            field=models.TextField(default='', null=True, verbose_name='Respuesta'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='indicaciones',
            field=models.TextField(default='', null=True, verbose_name='Indicación'),
        ),
    ]
