# Generated by Django 4.1 on 2022-10-03 17:46

import datetime
from django.db import migrations, models
import time


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0005_alter_formulariosrhistorial_comentarios_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosrderivacion',
            name='hora_derivado',
            field=models.TimeField(default=datetime.datetime.now, verbose_name='Hora Derivado'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='hora_ingreso',
            field=models.TimeField(default=time.time, verbose_name='Hora Ingreso'),
        ),
    ]
