# Generated by Django 4.1 on 2022-10-03 20:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0006_alter_formulariosrderivacion_hora_derivado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosrderivacion',
            name='id_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srderivacion', to='formularioSR.formulariosr', verbose_name='Id formularioSR'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='id_formulario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='srhistorial', to='formularioSR.formulariosr', verbose_name='Id formularioSR'),
        ),
    ]
