# Generated by Django 4.1 on 2022-12-16 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0008_alter_formulariosr_hora_ingreso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosrderivacion',
            name='fecha_derivado',
            field=models.DateField(verbose_name='Fecha Derivado'),
        ),
        migrations.AlterField(
            model_name='formulariosrderivacion',
            name='hora_derivado',
            field=models.TimeField(verbose_name='Hora Derivado'),
        ),
        migrations.AlterField(
            model_name='formulariosrderivacion',
            name='rut_derivado',
            field=models.CharField(blank=True, max_length=50, verbose_name='Rut Derivado'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='fecha_ingreso',
            field=models.DateField(verbose_name='Fecha Ingreso'),
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='hora_ingreso',
            field=models.TimeField(verbose_name='Hora Ingreso'),
        ),
    ]
