# Generated by Django 4.1 on 2022-12-21 14:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0009_alter_formulariosrderivacion_fecha_derivado_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='estado_solicitud',
            field=models.IntegerField(choices=[(1, 'INGRESADO'), (2, 'DERIVADO'), (3, 'SOLUCIONADO'), (4, 'SIN SOLUCIÓN')], verbose_name='Estado Solicitud'),
        ),
    ]
