# Generated by Django 4.1 on 2023-04-14 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('formularioSR', '0010_alter_formulariosrhistorial_estado_solicitud'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='formulariosr',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterField(
            model_name='formulariosrhistorial',
            name='estado_solicitud',
            field=models.IntegerField(choices=[(1, 'INGRESADO'), (2, 'DERIVADO'), (3, 'RESPONDIDO'), (4, 'SOLUCIONADO'), (5, 'SIN SOLUCIÓN')], verbose_name='Estado Solicitud'),
        ),
    ]
