# Generated by Django 4.1 on 2022-11-23 15:06

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('insumos', '0015_alter_insumo_categoria_alter_insumo_unidad_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='CierreMensual',
            fields=[
                ('id_cierre_mensual', models.AutoField(primary_key=True, serialize=False)),
                ('fecha_cierre', models.DateField(default=datetime.date.today, verbose_name='Fecha Cierre')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='CierreMensualInsumo',
            fields=[
                ('id_cierre_mensual_insumo', models.AutoField(primary_key=True, serialize=False)),
                ('id_insumo', models.IntegerField(verbose_name='Id Insumo')),
                ('codigo_insumo', models.IntegerField(verbose_name='Código Insumo')),
                ('saldo', models.IntegerField(verbose_name='Saldo')),
                ('precio', models.FloatField(verbose_name='Precio')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_categoria', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.categoria', verbose_name='Id Categoría')),
                ('id_cierre_mensual', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cierremensual_insumo', to='cierreMensual.cierremensual', verbose_name='Id Cierre Mensual')),
                ('id_unidad_medida', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cierreMensual.cierremensual', verbose_name='Id Cierre Mensual')),
            ],
        ),
    ]
