# Generated by Django 4.1 on 2022-11-23 19:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('insumos', '0015_alter_insumo_categoria_alter_insumo_unidad_medida'),
        ('cierreMensual', '0002_cierremensualinsumo_denominacion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cierremensualinsumo',
            name='id_unidad_medida',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.unidadmedida', verbose_name='Id Cierre Mensual'),
        ),
    ]
