# Generated by Django 4.1 on 2023-04-14 15:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cierreMensual', '0003_alter_cierremensualinsumo_id_unidad_medida'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cierremensual',
            options={'ordering': ['-pk']},
        ),
        migrations.AlterModelOptions(
            name='cierremensualinsumo',
            options={'ordering': ['-pk']},
        ),
    ]
