# Generated by Django 4.1 on 2022-08-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cuenta',
            name='anexo',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='cuenta',
            name='estado',
            field=models.BooleanField(default=True, verbose_name='Estado'),
        ),
    ]
