# Generated by Django 4.1 on 2022-08-31 16:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_cuenta_anexo_cuenta_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cuenta',
            name='anexo',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
