# Generated by Django 4.1 on 2022-09-21 13:05

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0005_alter_cuenta_anexo_alter_cuenta_usuario'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Cuenta',
            new_name='Profile',
        ),
    ]
