# Generated by Django 4.1 on 2022-09-21 13:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_rename_cuenta_profile'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='usuario',
            new_name='user',
        ),
    ]
