# Generated by Django 4.1 on 2022-09-22 15:14

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0008_alter_profile_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Perfil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_perfil', models.CharField(max_length=50, verbose_name='Nombre Perfil')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut', models.CharField(max_length=20, verbose_name='Rut')),
                ('anexo', models.IntegerField(blank=True, default=0, null=True, verbose_name='Anexo')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_perfil', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='user.perfil', verbose_name='Perfil')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='userprofile', to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
