# Generated by Django 4.1 on 2022-09-22 17:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0009_perfil_userprofile_delete_profile'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento', verbose_name='Departamento')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='Usuario')),
            ],
        ),
        migrations.CreateModel(
            name='UserCargo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_activacion', models.DateField(verbose_name='Fecha Activación')),
                ('fecha_desactivacion', models.DateField(verbose_name='Fecha Desactivación')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_cargo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='user.perfil', verbose_name='Cargo')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario', to='user.perfil', verbose_name='Usuario')),
            ],
        ),
    ]
