# Generated by Django 4.1 on 2022-09-22 20:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options_and_more'),
        ('user', '0012_alter_usercargo_fecha_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercargo',
            name='id_cargo',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='user.perfil', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='userdepartamento',
            name='id_departamento',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento', verbose_name='Departamento'),
        ),
    ]
