# Generated by Django 4.1 on 2022-09-22 21:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_userprofile_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='id_perfil',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.PROTECT, to='user.perfil', verbose_name='Perfil'),
        ),
    ]
