# Generated by Django 4.1 on 2022-09-22 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_userprofile_id_perfil'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercargo',
            name='fecha_activacion',
            field=models.DateField(null=True, verbose_name='Fecha Activación'),
        ),
        migrations.AlterField(
            model_name='usercargo',
            name='fecha_desactivacion',
            field=models.DateField(null=True, verbose_name='Fecha Desactivación'),
        ),
    ]
