# Generated by Django 4.1 on 2022-09-23 12:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_usercargo_fecha_activacion_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercargo',
            name='fecha_activacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Activación'),
        ),
        migrations.AlterField(
            model_name='usercargo',
            name='fecha_desactivacion',
            field=models.DateField(blank=True, null=True, verbose_name='Fecha Desactivación'),
        ),
    ]
