# Generated by Django 4.1 on 2022-09-23 14:48

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0019_alter_usercargo_id_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdepartamento',
            name='id_sub_departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_subdpto', to='departamentos.subdepartamento', verbose_name='Sub Departamento'),
        ),
        migrations.AddField(
            model_name='userdepartamento',
            name='id_unidad',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_unidad', to='departamentos.unidad', verbose_name='Unidad'),
        ),
        migrations.AlterField(
            model_name='usercargo',
            name='id_cargo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='user.perfil', verbose_name='Cargo'),
        ),
        migrations.AlterField(
            model_name='usercargo',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_cargo', to=settings.AUTH_USER_MODEL, verbose_name='Usuario'),
        ),
        migrations.AlterField(
            model_name='userdepartamento',
            name='id_departamento',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='usuario_dpto', to='departamentos.departamento', verbose_name='Departamento'),
        ),
        migrations.AlterField(
            model_name='userdepartamento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL, verbose_name='usuario_dpto'),
        ),
    ]
