# Generated by Django 4.1 on 2022-09-23 17:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cargos', '0001_initial'),
        ('user', '0020_userdepartamento_id_sub_departamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usercargo',
            name='id_cargo',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.PROTECT, related_name='cargo', to='cargos.cargo', verbose_name='Cargo'),
        ),
    ]
