# Generated by Django 4.1 on 2022-11-10 17:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0027_alter_userdepartamento_id_usuario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='rut',
            field=models.CharField(max_length=20, unique=True, verbose_name='Rut'),
        ),
    ]
