# Generated by Django 4.1 on 2022-11-21 14:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0028_alter_userprofile_rut'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userprofile',
            options={'ordering': ['id']},
        ),
    ]
