# Generated by Django 4.1 on 2022-11-30 14:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('user', '0029_alter_userprofile_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdepartamento',
            name='id_usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='usuario_id_dpto', to=settings.AUTH_USER_MODEL, verbose_name='usuario_id_dpto'),
        ),
    ]
