# Generated by Django 4.1 on 2022-12-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0030_alter_userdepartamento_id_usuario'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='perfil',
            options={'ordering': ['id']},
        ),
    ]
