# Generated by Django 4.1 on 2022-10-04 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('proveedores', '0001_initial'),
        ('insumos', '0012_alter_insumo_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Compra',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_compra', models.DateField(verbose_name='Fecha Compra')),
                ('guia', models.CharField(max_length=50, verbose_name='Guía')),
                ('orden_de_compra', models.CharField(max_length=50, verbose_name='Orden de Compra')),
                ('total_compra', models.IntegerField(verbose_name='Total Compra')),
                ('descuento', models.IntegerField(verbose_name='Descuento')),
                ('fecha_ingreso_compra', models.DateField(verbose_name='Fecha Ingreso Compra')),
                ('rut_responsable', models.CharField(max_length=50, verbose_name='RUT Responsable')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_proveedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='proveedores.proveedor', verbose_name='Proveedor')),
            ],
        ),
        migrations.CreateModel(
            name='CompraInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField(verbose_name='Cantidad')),
                ('precio_unitario', models.FloatField(verbose_name='Precio Unitario')),
                ('precio_promedio', models.FloatField(verbose_name='Precio Promedio')),
                ('precio_con_iva', models.FloatField(verbose_name='Precio con IVA')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('id_compra', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='compras.compra', verbose_name='Compra')),
                ('id_insumo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='insumos.insumo', verbose_name='Insumo')),
            ],
        ),
    ]
