# Generated by Django 4.1 on 2022-10-11 19:11

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compra',
            name='fecha_ingreso_compra',
            field=models.DateField(default=datetime.date.today, verbose_name='Fecha Ingreso Compra'),
        ),
    ]
