# Generated by Django 4.1 on 2023-04-24 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('compras', '0003_alter_compra_options_alter_compra_guia_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='compra',
            options={'ordering': ['-id']},
        ),
    ]
