# Generated by Django 4.1 on 2022-10-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rut_proveedor', models.CharField(max_length=50, verbose_name='RUT Proveedor')),
                ('nombre_proveedor', models.CharField(max_length=50, verbose_name='Nombre Proveedor')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
    ]
