# Generated by Django 4.1 on 2023-04-14 15:57

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('proveedores', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='proveedor',
            name='rut_proveedor',
            field=models.CharField(max_length=50, validators=[django.core.validators.RegexValidator('^\\d{1,2}\\.\\d{3}\\.\\d{3}[-][0-9kK]{1}$', message='Ingresar un rut válido (Ej: 12345678-9)')], verbose_name='RUT Proveedor'),
        ),
    ]
