# Generated by Django 4.1 on 2022-08-09 14:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_dpto', models.IntegerField(unique=True, verbose_name='Id Departamento')),
                ('nombre_dpto', models.CharField(max_length=100, verbose_name='Nombre departamento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
            ],
        ),
        migrations.CreateModel(
            name='Subdepartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_sub_dpto', models.IntegerField(unique=True, verbose_name='Id Sub Departamento')),
                ('nombre_sub_dpto', models.CharField(max_length=100, verbose_name='Nombre Sub-Departamento')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('departamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.departamento', verbose_name='pertenece al departamento')),
            ],
        ),
        migrations.CreateModel(
            name='Unidad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_unidad', models.IntegerField(unique=True, verbose_name='Id Unidad')),
                ('nombre_unidad', models.CharField(max_length=100, verbose_name='Nombre Unidad')),
                ('estado', models.BooleanField(default=True, verbose_name='Estado')),
                ('subdepartamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='departamentos.subdepartamento', verbose_name='pertenece al Sub-departamento')),
            ],
        ),
    ]
