# Generated by Django 4.1 on 2022-08-23 13:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='subdepartamento',
            options={'verbose_name': 'Sub-Departamento', 'verbose_name_plural': 'Sub-Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'verbose_name': 'Unidad', 'verbose_name_plural': 'Secciones'},
        ),
    ]
