# Generated by Django 4.1 on 2022-09-28 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0002_alter_departamento_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unidad',
            name='subdepartamento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='unidad_sub_dpto', to='departamentos.subdepartamento', verbose_name='pertenece al Sub-departamento'),
        ),
    ]
