# Generated by Django 4.1 on 2022-11-14 18:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0006_alter_departamento_rut_jefe_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='departamento',
            options={'ordering': ['id_dpto'], 'verbose_name': 'Departamento', 'verbose_name_plural': 'Departamentos'},
        ),
    ]
