# Generated by Django 4.1 on 2022-12-06 21:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('departamentos', '0007_alter_departamento_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='subdepartamento',
            options={'ordering': ['id_sub_dpto'], 'verbose_name': 'Sub-Departamento', 'verbose_name_plural': 'Sub-Departamentos'},
        ),
        migrations.AlterModelOptions(
            name='unidad',
            options={'ordering': ['id_unidad'], 'verbose_name': 'Unidad', 'verbose_name_plural': 'Secciones'},
        ),
    ]
